name: Build and Release Windows

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-windows.yml

  release:
    needs: build
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Download installer artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ needs.build.outputs.exe_uploaded_artifact_name }}
      - name: Download ZIP artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ needs.build.outputs.zip_uploaded_artifact_name }}
      - name: Upload release artifacts
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            ${{ needs.build.outputs.exe_artifact_versioned_name }}
            ${{ needs.build.outputs.zip_artifact_versioned_name }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-west-1
      - name: Define artifact names
        id: define-artifact-names
        run: |
          echo exe_artifact_name=arelle-win.exe >> $GITHUB_OUTPUT
          echo zip_artifact_name=arelle-win.zip >> $GITHUB_OUTPUT
      - name: Upload release artifacts to S3
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          aws s3 cp --acl public-read ${{ needs.build.outputs.exe_artifact_versioned_name }} s3://arelle-us/${{ needs.build.outputs.exe_artifact_versioned_name }}
          aws s3 cp --acl public-read ${{ needs.build.outputs.zip_artifact_versioned_name }} s3://arelle-us/${{ needs.build.outputs.zip_artifact_versioned_name }}
          aws s3 cp --acl public-read s3://arelle-us/${{ needs.build.outputs.exe_artifact_versioned_name }} s3://arelle-us/${{ steps.define-artifact-names.outputs.exe_artifact_name }}
          aws s3 cp --acl public-read s3://arelle-us/${{ needs.build.outputs.zip_artifact_versioned_name }} s3://arelle-us/${{ steps.define-artifact-names.outputs.zip_artifact_name }}
      - name: Configure Ali Cloud Credentials
        uses: yizhoumo/setup-ossutil@v1.1.3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          endpoint: oss-cn-shenzhen.aliyuncs.com
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - name: Upload release artifacts to Ali Cloud
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ossutil cp -f ${{ needs.build.outputs.exe_artifact_versioned_name }} oss://arelle-cn/${{ needs.build.outputs.exe_artifact_versioned_name }}
          ossutil cp -f ${{ needs.build.outputs.zip_artifact_versioned_name }} oss://arelle-cn/${{ needs.build.outputs.zip_artifact_versioned_name }}
          ossutil create-symlink oss://arelle-cn/${{ steps.define-artifact-names.outputs.exe_artifact_name }} oss://arelle-cn/${{ needs.build.outputs.exe_artifact_versioned_name }}
          ossutil create-symlink oss://arelle-cn/${{ steps.define-artifact-names.outputs.zip_artifact_name }} oss://arelle-cn/${{ needs.build.outputs.zip_artifact_versioned_name }}
