name: Run Integration Tests

on:
  workflow_dispatch:
  pull_request_target:
    paths:
      - '**.py'
      - '**.pyw'
      - '.github/actions/get_conformance_suites_matrix/**'
      - '.github/actions/get_test_scripts_matrix/**'
      - '.github/actions/test_conformance_suite/**'
      - '.github/actions/test_script/**'
      - '.github/workflows/integration-tests.yml'
      - 'arelle/**'
      - 'requirements*.txt'
      - 'tests/**'

permissions: {}

jobs:
  find-conformance-suites:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.build-conformance-suite-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      # pull_request_target runs in the context of the base repository, so we need to
      # merge the head branch to test the correct code for the PR.
      - uses: ./.github/actions/merge
        with:
          commit_sha: ${{ github.event.pull_request.head.sha }}
          repository_full_name: ${{ github.event.pull_request.head.repo.full_name }}
      - id: build-conformance-suite-matrix
        uses: ./.github/actions/get_conformance_suites_matrix

  find-test-scripts:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.build-test-script-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/merge
        with:
          commit_sha: ${{ github.event.pull_request.head.sha }}
          repository_full_name: ${{ github.event.pull_request.head.repo.full_name }}
      - id: build-test-script-matrix
        uses: ./.github/actions/get_test_scripts_matrix

  run-conformance-suite:
    name: ${{ matrix.test.short_name }}${{ matrix.test.shard && format(':{0}', matrix.test.shard) || '' }} - ${{ matrix.test.os }} - ${{ matrix.test.python_version }}
    needs: find-conformance-suites
    runs-on: ${{ matrix.test.os }}
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.find-conformance-suites.outputs.matrix) }}
    environment: ${{ matrix.test.environment }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/merge
        with:
          commit_sha: ${{ github.event.pull_request.head.sha }}
          repository_full_name: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Configure AWS Credentials
        if: ${{ matrix.test.environment == 'integration-tests' }}
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Test Conformance Suite
        uses: ./.github/actions/test_conformance_suite
        with:
          name: ${{ matrix.test.name }}
          python_version: ${{ matrix.test.python_version }}
          shard: ${{ matrix.test.shard }}
          short_name: ${{ matrix.test.short_name }}

  run-test-script:
    name: scripts - ${{ matrix.test.private && 'private - ' || '' }}${{ matrix.test.os }} - ${{ matrix.test.python_version }}
    needs: find-test-scripts
    runs-on: ${{ matrix.test.os }}
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.find-test-scripts.outputs.matrix) }}
    environment: ${{ matrix.test.environment }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/merge
        with:
          commit_sha: ${{ github.event.pull_request.head.sha }}
          repository_full_name: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Configure AWS Credentials
        if: ${{ matrix.test.environment == 'integration-tests' }}
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Test Script
        uses: ./.github/actions/test_script
        with:
          artifact_name: ${{ matrix.test.private && 'private' || '' }} scripts ${{ matrix.test.os }} ${{ matrix.test.python_version }} logs
          name: ${{ matrix.test.name }}
          python_version: ${{ matrix.test.python_version }}
