name: Build and publish python package

on:
  pull_request:
  release:
    types: [created]

jobs:
  build-and-publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Install Python 3
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.9'
      - name: Build python package
        run: |
          pip install setuptools wheel twine build
          python -m build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: arelle.tar.gz
          path: dist/*.tar.gz
      - name: Publish package on release
        if: startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload dist/*
