name: Build and publish python package

on:
  workflow_call:
    inputs:
      python_version:
        default: '3.14.2'
        description: 'Python version to use'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      python_version:
        default: '3.14.2'
        description: 'Python version to use'
        required: true
        type: string

permissions: {}

jobs:
  build-package:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout arelle
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v6.2.0
        with:
          cache: 'pip'
          check-latest: true
          python-version: ${{ inputs.python_version }}
      - name: Build python package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install build
          python -m build
      - name: Upload tar artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: arelle.tar.gz
          if-no-files-found: error
          path: dist/*.tar.gz
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: arelle.whl
          if-no-files-found: error
          path: dist/*.whl
