name: Build and publish python package

on:
  workflow_dispatch:
    inputs:
      python_version:
        default: '3.10'
        description: 'Python version to use'
        required: true
        type: string

jobs:
  build-package:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout arelle
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4.3.0
        with:
          cache: 'pip' # caching pip dependencies
          check-latest: true
          python-version: ${{ inputs.python_version }}
      - name: Build python package
        run: |
          pip install -U setuptools wheel
          pip install build
          python -m build
      - name: Upload tar artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: arelle.tar.gz
          path: dist/*.tar.gz
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: arelle.whl
          path: dist/*.whl

  publish-package:
    if: startsWith(github.ref, 'refs/tags')
    needs: build-package
    environment: release
    runs-on: ubuntu-22.04
    steps:
      - name: Install twine
        run: pip install -U twine
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.1
      - name: Publish package on release
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload */*
