name: Run Test Scripts

on:
  workflow_dispatch:

permissions: {}

jobs:
  find-test-scripts:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.build-test-script-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - id: build-test-script-matrix
        uses: ./.github/actions/get_test_scripts_matrix

  run-test-script:
    name: ${{ matrix.test.private && 'private - ' || '' }}${{ matrix.test.os }} - ${{ matrix.test.python_version }}
    needs: find-test-scripts
    runs-on: ${{ matrix.test.os }}
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.find-test-scripts.outputs.matrix) }}
    environment: ${{ matrix.test.environment }}
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Configure AWS Credentials
        if: ${{ matrix.test.environment == 'integration-tests' }}
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Test Script
        uses: ./.github/actions/test_script
        with:
          artifact_name: ${{ matrix.test.private && 'private' || '' }} scripts ${{ matrix.test.os }} ${{ matrix.test.python_version }} logs
          name: ${{ matrix.test.name }}
          python_version: ${{ matrix.test.python_version }}
