name: Run Integration Test Scripts (Parallel)

on:
  workflow_dispatch:

permissions: {}

jobs:
  find-tests:
    runs-on: ubuntu-24.04
    outputs:
      names: ${{ steps.get-test-names.outputs.names }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - id: get-test-names
        run: echo "names=$(find tests/integration_tests/scripts/tests \( -name "*.py" \) | xargs basename -a | sed 's/\.[^.]*$//' |  jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  run-test:
    name: ${{ matrix.name }} - ${{ matrix.os }} - ${{ matrix.python-version }}
    needs: find-tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: ${{ fromJson(needs.find-tests.outputs.names) }}
        os:
          - macos-14
          - ubuntu-24.04
          - windows-2022
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install Python 3
        uses: actions/setup-python@v5.3.0
        with:
          cache: 'pip'
          check-latest: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-test.txt
          pip install -r requirements-plugins.txt
      - name: Run integration tests with pytest
        run: |
          pytest -s --disable-warnings --name="${{ matrix.name }}" --download-cache --offline --arelle="python arelleCmdLine.py" tests/integration_tests/scripts/test_scripts.py
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ matrix.name }}_${{ matrix.os }}_${{ matrix.python-version }}_logs
          if-no-files-found: error
          include-hidden-files: true
          path: '.test/**/*.logfile.*'
